# Generated by Django 4.0 on 2021-12-18 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_members_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='isDeleted',
        ),
    ]
