# Generated by Django 4.0 on 2021-12-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_member_isdeleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
